Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Models/Student.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace WebAppExamJobMVC.Models
{
    public class Student
    {
        public int StudentId { get; set; }

        [Required(ErrorMessage = "Поле 'Имя' обязательно для заполнения.")]
        [DisplayName("Имя")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Поле 'Фамилия' обязательно для заполнения.")]
        [DisplayName("Фамилия")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Поле 'Группа' обязательно для заполнения.")]
        [DisplayName("Группа")]
        public string Group { get; set; }

        [DisplayName("Телефон")]
        public string Phone { get; set; }

        [DisplayName("Электронная почта")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Поле 'Оценка' обязательно для заполнения.")]
        [Range(1, 5, ErrorMessage = "Сумма должна быть в пределах от 1 до 5.")]
        [DisplayName("Оценка")]
        public int? Score { get; set; }

        [DisplayName("Учебная дисциплина")]
        public int DisciplineId { get; set; }

        [DisplayName("Учебная дисциплина")]
        public Discipline Discipline { get; set; }
    }
}

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppExamJobMVC.Models;

namespace WebAppExamJobMVC.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        private readonly StudentContext _context;

        public StudentsController(StudentContext context)
        {
            _context = context;
        }


        // GET: Students
        public async Task<IActionResult> Index()
        {
            var studentContext = _context.Students.Include(s => s.Discipline);
            return View(await studentContext.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.Discipline)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "Id", "Name");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StudentId,FirstName,LastName,Group,Phone,Email,Score,DisciplineId")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "Id", "Name", student.DisciplineId);
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "Id", "Name", student.DisciplineId);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StudentId,FirstName,LastName,Group,Phone,Email,Score,DisciplineId")] Student student)
        {
            if (id != student.StudentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DisciplineId"] = new SelectList(_context.Disciplines, "Id", "Name", student.DisciplineId);
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.Discipline)
                .FirstOrDefaultAsync(m => m.StudentId == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            if (student != null)
            {
                _context.Students.Remove(student);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.StudentId == id);
        }



        // Сумма баллов
        public IActionResult TotalScore()
        {
            var totalScore = _context.Students.Sum(s => s.Score);
            return View(totalScore);
        }

        // Пять лучших студентов
        public IActionResult TopStudents()
        {
            var topStudents = _context.Students.OrderByDescending(s => s.Score).Take(5).Include(s => s.Discipline).ToList();
            return View(topStudents);
        }

        // Пять худших студентов
        public IActionResult BottomStudents()
        {
            var bottomStudents = _context.Students.OrderBy(s => s.Score).Take(5).Include(s => s.Discipline).ToList();
            return View(bottomStudents);
        }

        // Экспорт в текстовый файл
        public IActionResult ExportToFile()
        {
            var students = _context.Students.Include(s => s.Discipline).ToList();
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "students.txt");
            using (var writer = new StreamWriter(filePath))
            {
                foreach (var student in students)
                {
                    writer.WriteLine($"{student.FirstName} {student.LastName} {student.Group} {student.Phone} {student.Email} ({student.Discipline.Name}): {student.Score}");
                }
            }
            return File("/students.txt", "text/plain", "students.txt");
        }

    }
}

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/BottomStudents.cshtml
@model IEnumerable<WebAppExamJobMVC.Models.Student>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<h2>Пять худших студентов</h2>

<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Учебная дисциплина</th>
            <th>Оценка</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.FirstName</td>
                <td>@student.LastName</td>
                <td>@student.Discipline.Name</td>
                <td>@student.Score</td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Students" asp-action="Index">Назад к списку студентов</a>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/Create.cshtml
@model WebAppExamJobMVC.Models.Student

@{
    ViewData["Title"] = "Создание нового студента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создание нового студента</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisciplineId" class="control-label"></label>
                <select asp-for="DisciplineId" class ="form-control" asp-items="ViewBag.DisciplineId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" style="margin-top: 10px;" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style="margin-top: 10px;">Вернуться в список</a>
</div>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/Delete.cshtml
@model WebAppExamJobMVC.Models.Student

@{
    ViewData["Title"] = "Удалить студента";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удалить студента</h2>

<h3>Вы уверены, что хотите удалить данного студента?</h3>
<div>
    <h4>Студент</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discipline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discipline.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StudentId" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться в список</a>
    </form>
</div>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/Details.cshtml
@model WebAppExamJobMVC.Models.Student

@{
    ViewData["Title"] = "Подробнее о студенте";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Подробнее о студенте</h2>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Group)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Group)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Score)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Score)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discipline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discipline.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.StudentId">Изменить</a> |
    <a asp-action="Index">Вернуться в список</a>
</div>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/Edit.cshtml
@model WebAppExamJobMVC.Models.Student

@{
    ViewData["Title"] = "Изменить данные о студенте";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Изменить данные о студенте</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StudentId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Group" class="control-label"></label>
                <input asp-for="Group" class="form-control" />
                <span asp-validation-for="Group" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Score" class="control-label"></label>
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisciplineId" class="control-label"></label>
                <select asp-for="DisciplineId" class="form-control" asp-items="ViewBag.DisciplineId"></select>
                <span asp-validation-for="DisciplineId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" style="margin-top: 10px;" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style="margin-top: 10px;">Вернуться в список</a>
</div>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/ExportToFile.cshtml
@model IEnumerable<WebAppExamJobMVC.Models.Student>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<h2>Экспорт студентов в текстовый файл</h2>

<p>Файл с данными студентов был успешно создан. Вы можете <a href="/students.txt">скачать его здесь</a>.</p>

<a asp-controller="Students" asp-action="Index">Назад к списку студентов</a>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/Index.cshtml
@model IEnumerable<WebAppExamJobMVC.Models.Student>

@{
    ViewData["Title"] = "Студенты";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Студенты</h2>

<p>
    <a asp-action="Create" style="margin-right: 10px;">Создать нового студента</a>
    <a asp-controller="Students" asp-action="TotalScore" style="margin-right: 10px;">Сумма баллов</a>
    <a asp-controller="Students" asp-action="TopStudents" style="margin-right: 10px;">Пять лучших студентов</a>
    <a asp-controller="Students" asp-action="BottomStudents" style="margin-right: 10px;">Пять худших студентов</a>
    <a asp-controller="Students" asp-action="ExportToFile" style="margin-right: 10px;">Экспорт в текстовый файл</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Group)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Score)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discipline)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discipline.Name)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.StudentId">Изменить</a> |
                    <a asp-action="Details" asp-route-id="@item.StudentId">Подробнее</a> |
                    <a asp-action="Delete" asp-route-id="@item.StudentId">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/TopStudents.cshtml
@model IEnumerable<WebAppExamJobMVC.Models.Student>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<h2>Пять лучших студентов</h2>

<table class="table">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Учебная дисциплина</th>
            <th>Оценка</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.FirstName</td>
                <td>@student.LastName</td>
                <td>@student.Discipline.Name</td>
                <td>@student.Score</td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Students" asp-action="Index">Назад к списку студентов</a>

Itmo.Labs/ASP.NET_Examination job/WebAppExamJobMVC/Views/Students/TotalScore.cshtml
@model int

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<h2>Сумма баллов студентов</h2>
<p>Общая сумма баллов: <strong>@Model</strong></p>

<a asp-controller="Students" asp-action="Index">Назад к списку студентов</a>